name: 'Build and test container'
description: 'Builds and tests container'
inputs:
  build-context:  # id of input
    description: 'The folder to build'
    required: true
  dockerfile:  # id of input
    description: 'The filename found in build context '
    required: true
  image-name:
    description: 'Image name without tags eg. frontend'
    required: true
  test-command:
    description: 'The test command to run'
    required: true
    default: 'yarn test'
  gcp-project:
    description: 'GCP project id'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and export to Docker
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.build-context }}
        file: ./${{ inputs.build-context }}/${{inputs.dockerfile}}
        tags: ${{inputs.image-name}}-test
        load: true
    - name: Test
      id: test
      shell: bash
      run: |
          docker run --rm ${{inputs.image-name}}-test ${{ inputs.test-command }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.build-context }}
        file: ./${{ inputs.build-context}}/${{inputs.dockerfile}}
        push: true
        tags: europe-docker.pkg.dev/${{ inputs.gcp-project }}/feedbackly/${{ inputs.image-name }}:${{ github.sha }}

