
name: "Build context two"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # build 
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./build-context-two
          file: ./build-context-two/Dockerfile
          push: false
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}