
name: "Build context one"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      # Access token for docker image registry
      - name: Generate Access Token
        id: generate_access_token
        run: |
          echo "::set-output name=token::$(gcloud auth print-access-token)"
      # build 
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./build-context-one
          file: ./build-context-one/Dockerfile
          push: true
          registry: europe-docker.pkg.dev
          repository: ${{ secrets.GCP_PROJECT_ID }}/feedbackly/build1
          tags: ${{ env.GITHUB_SHA }}
          username: oauth2accesstoken
          password: ${{ steps.generate_access_token.outputs.token }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}