
name: "Build context one"
on: [push]
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: feedbackly    # TODO: update to cluster name
  GKE_ZONE: europe-north1	   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-hello-app # TODO: update deployment name if changed in deployment.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      # build 
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: europe-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./build-context-one
      #     file: ./build-context-one/Dockerfile
      #     push: true
      #     tags: europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/feedbackly/build1:${{ github.sha }}
      - name: Build and test context 1
        uses: './.github/actions/build-and-test/action.yml'
        with:
          build-context: ./build-context-one
          dockerfile: dockerfile
          image-name: buildd1
          test-command: echo 'yay'
      - run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
      - name: Deploy
        run: |-
          kubectl apply -n branch-${{ steps.extract_branch.outputs.branch }} -k ./kustomize
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n branch-${{ steps.extract_branch.outputs.branch }}
          kubectl get services -o wide -n branch-${{ steps.extract_branch.outputs.branch }}